# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AAIDrive
email: hufman@gmail.com
description: > # this means to ignore newlines until "homeurl:"
  Implementations of some Android Auto features as unofficial IDrive apps
homeurl: "https://github.com/BimmerGestalt/AAIdrive"
baseurl: "/AAIdrive" # the subpath of your site, e.g. /blog
url: "https://bimmergestalt.github.io" # the base hostname & protocol for your site
github_username:  hufman

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
