name: build  # used as the badge name

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  unitTest:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        map: [Nomap, Gmap]
        analytics: [Nonalytics, Sentry]

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare cached external dependencies
        uses: actions/cache@v2
        with:
          key: aaidrive_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            - external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build the project
        run: ./gradlew compileDebug
      - name: Run unit tests
        run: ./gradlew test${{ matrix.map }}${{ matrix.analytics }}DebugUnitTestCoverage
      - name: Upload CodeCov report
        if: github.event.pull_request.title != 'New Crowdin updates' && github.event.ref != 'refs/heads/l10n_main'   # don't upload coverage for Crowdin pushes
        uses: codecov/codecov-action@v1
        with:
          file: app/build/reports/jacoco/jacoco.xml
          flags: unittests


  instrumentedTest:
    runs-on: macos-latest
    strategy:
      matrix:
        map: [Nomap, Gmap]
        hasSecret:
          - ${{ github.repository == 'BimmerGestalt/AAIdrive' && github.event_name == 'push' }}
        exclude:  # don't run Gmap tests if we are in a context that doesn't have the gmap secret
          - hasSecret: false
            map: Gmap
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare cached external dependencies
        uses: actions/cache@v2
        with:
          key: aaidrive_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            - external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action
      - name: Build the project
        run: ./gradlew compileDebug
      - name: Prepare emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          emulator-build: 6110076
          target: google_apis
          script: adb install external/BMW_Connected_v3.1.1.3078_apkpure.com.apk
      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          AndroidAutoIdrive_GmapsApiKey: ${{ secrets.ANDROIDAUTOIDRIVE_GMAPSAPIKEY }}
        with:
          force-avd-creation: false
          api-level: 28
          emulator-build: 6110076
          target: google_apis
          script: ./gradlew connected${{ matrix.map }}NonalyticsDebugAndroidTestCoverage
      - name: Upload CodeCov report
        if: matrix.map != 'Gmap' && github.event.pull_request.title != 'New Crowdin updates' && github.event.ref != 'refs/heads/l10n_main'   # don't upload Gmap test results, which don't run during PRs
        uses: codecov/codecov-action@v1
        with:
          file: app/build/reports/jacoco/jacoco.xml
#          flags: instrumentedtests

# android connectedTests don't leave the app or files installed after the test
# so we have to invoke it manually
      - name: Generate screenshots
        uses: reactivecircus/android-emulator-runner@v2
        env:
          AndroidAutoIdrive_GmapsApiKey: ${{ secrets.ANDROIDAUTOIDRIVE_GMAPSAPIKEY }}
        with:
          force-avd-creation: false
          api-level: 28
          emulator-build: 6110076
          target: google_apis
          script: adb logcat -c && ./gradlew install${{ matrix.map }}NonalyticsDebug && ./gradlew install${{ matrix.map }}NonalyticsDebugAndroidTest && ( adb shell am instrument -w me.hufman.androidautoidrive.test/me.hufman.androidautoidrive.DexOpenerAndroidJUnitRunner || adb shell am instrument -w me.hufman.androidautoidrive.test/me.hufman.androidautoidrive.DexOpenerAndroidJUnitRunner ) && ./gradlew fetchScreenshots || adb logcat -d
      - name: Package screenshots
        uses: actions/upload-artifact@v2
        if: matrix.map == 'Nomap'
        with:
          retention-days: 7
          name: screenshots
          path: |
            app/build/reports/androidTests/connected/screenshots/*

  package:
    # Only build on the main repo, which has the secrets configured
    if: github.repository == 'BimmerGestalt/AAIdrive' && github.event_name == 'push'
    needs: [unitTest]  # wait for the tests to succeed
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare cached external dependencies
        uses: actions/cache@v2
        with:
          key: aaidrive_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            - external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action
      - name: Extract signing key
        run: "echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > keystore.jks"
      - name: Build production artifacts
        run: ./gradlew assembleNomap
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: upload
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          AndroidAutoIdrive_SpotifyApiKey: ${{ secrets.ANDROIDAUTOIDRIVE_SPOTIFYAPIKEY }}
          AndroidAutoIdrive_SentryDsn: ${{ secrets.ANDROIDAUTOIDRIVE_SENTRYDSN }}

      - name: Calculate APK hashes
        run: "find app/build/outputs/apk -name '*.apk' -execdir sha1sum {} \\;"
      - name: Confirm APK hashes
        run: "find app/build/outputs/apk -name '*.sha1' -exec cat {} \\; -execdir sha1sum -c {} \\;"
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          retention-days: 7
          name: apk
          path: |
            app/build/outputs/apk/nomapNonalytics/release/*apk
            app/build/outputs/apk/nomapNonalytics/release/*apk.sha1
            app/build/outputs/apk/nomapSentry/release/*apk
            app/build/outputs/apk/nomapSentry/release/*apk.sha1

  upload_s3:
    if: github.event_name == 'push'
    needs: package
    runs-on: ubuntu-18.04
    steps:
      - name: Download project artifacts
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: Determine branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Stage upload directory
        run: |
          mkdir dist
          cp nomapNonalytics/release/*apk dist/androidautoidrive-latest-${BRANCH_NAME}-nomap-nonalytics-release.apk
          cp nomapSentry/release/*apk dist/androidautoidrive-latest-${BRANCH_NAME}-nomap-sentry-release.apk
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@v1.1.3
        with:
          source_dir: dist
          destination_dir: aaidrive/builds
          aws_bucket: bimmergestalt
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  upload_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-18.04
    steps:
      - name: Download project artifacts
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: Stage upload directory
        run: |
          mkdir dist
          cp */release/*apk* dist/
      - name: Upload to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist/*
          overwrite: true
